#pragma once

#include "Rect.h"

enum 
{
	TEXTURE_UNITYCHAN_BRAKE_1,
	TEXTURE_UNITYCHAN_BRAKE_2,
	TEXTURE_UNITYCHAN_BRAKE_3,
	TEXTURE_UNITYCHAN_BRAKE_4,
	TEXTURE_UNITYCHAN_BRAKE_5,
	TEXTURE_UNITYCHAN_BRAKE_6,
	TEXTURE_UNITYCHAN_BRAKE_7,
	TEXTURE_UNITYCHAN_BRAKE_8,
	TEXTURE_UNITYCHAN_BRAKE_9,
	TEXTURE_UNITYCHAN_BRAKE_10,
	TEXTURE_UNITYCHAN_BRAKE_11,
	TEXTURE_UNITYCHAN_BRAKE_12,
	TEXTURE_UNITYCHAN_BRAKE_13,
	TEXTURE_UNITYCHAN_BRAKE_14,
	TEXTURE_UNITYCHAN_BRAKE_15,
	TEXTURE_UNITYCHAN_BRAKE_16,
	TEXTURE_UNITYCHAN_BRAKE_17,
	TEXTURE_UNITYCHAN_DAMAGE_1,
	TEXTURE_UNITYCHAN_DAMAGE_2,
	TEXTURE_UNITYCHAN_DAMAGE_3,
	TEXTURE_UNITYCHAN_DAMAGE_4,
	TEXTURE_UNITYCHAN_DAMAGE_5,
	TEXTURE_UNITYCHAN_HUNDGUN1_1,
	TEXTURE_UNITYCHAN_HUNDGUN1_2,
	TEXTURE_UNITYCHAN_HUNDGUN1_3,
	TEXTURE_UNITYCHAN_HUNDGUN1_4,
	TEXTURE_UNITYCHAN_HUNDGUN1_5,
	TEXTURE_UNITYCHAN_HUNDGUN1_6,
	TEXTURE_UNITYCHAN_HUNDGUN1_7,
	TEXTURE_UNITYCHAN_HUNDGUN1_8,
	TEXTURE_UNITYCHAN_HUNDGUN1_9,
	TEXTURE_UNITYCHAN_HUNDGUN1_10,
	TEXTURE_UNITYCHAN_HUNDGUN1_11,
	TEXTURE_UNITYCHAN_HUNDGUN1_12,
	TEXTURE_UNITYCHAN_HUNDGUN1_13,
	TEXTURE_UNITYCHAN_HUNDGUN1_14,
	TEXTURE_UNITYCHAN_HUNDGUN1_15,
	TEXTURE_UNITYCHAN_HUNDGUN1_16,
	TEXTURE_UNITYCHAN_HUNDGUN1_17,
	TEXTURE_UNITYCHAN_HUNDGUN1_18,
	TEXTURE_UNITYCHAN_HUNDGUN1_19,
	TEXTURE_UNITYCHAN_HUNDGUN1_20,
	TEXTURE_UNITYCHAN_IDLE_1,
	TEXTURE_UNITYCHAN_IDLE_2,
	TEXTURE_UNITYCHAN_IDLE_3,
	TEXTURE_UNITYCHAN_IDLE_4,
	TEXTURE_UNITYCHAN_JUMP_1,
	TEXTURE_UNITYCHAN_JUMP_2,
	TEXTURE_UNITYCHAN_JUMP_3,
	TEXTURE_UNITYCHAN_JUMP_FALL_1,
	TEXTURE_UNITYCHAN_JUMP_FALL_2,
	TEXTURE_UNITYCHAN_JUMP_LANDING,
	TEXTURE_UNITYCHAN_JUMP_UP_1,
	TEXTURE_UNITYCHAN_JUMP_UP_2,
	TEXTURE_UNITYCHAN_RUN_1,
	TEXTURE_UNITYCHAN_RUN_2,
	TEXTURE_UNITYCHAN_RUN_3,
	TEXTURE_UNITYCHAN_RUN_4,
	TEXTURE_UNITYCHAN_RUN_5,
	TEXTURE_UNITYCHAN_RUN_6,
	TEXTURE_UNITYCHAN_RUN_7,
	TEXTURE_UNITYCHAN_RUN_8,
	TEXTURE_UNITYCHAN_RUN_9,
	TEXTURE_UNITYCHAN_RUN_10,
	TEXTURE_UNITYCHAN_RUN_11,
	TEXTURE_UNITYCHAN_RUN_12,
	TEXTURE_UNITYCHAN_RUN_13,
	TEXTURE_UNITYCHAN_RUN_14,
	TEXTURE_UNITYCHAN_RUN_15,
	TEXTURE_UNITYCHAN_RUN_16,
	TEXTURE_UNITYCHAN_RUN_17,
	TEXTURE_UNITYCHAN_RUN_18,
	TEXTURE_UNITYCHAN_MAX
};

class Textrure
{
public:
	const char * m_fileName;
	unsigned int m_texture;
	//当たり判定
	Rect m_bound;

	//それぞれのクラスの初期化
	int Init();

	//すべてのクラスを初期化する
	static int InitAll();
};

extern Textrure g_textures[TEXTURE_UNITYCHAN_MAX];



